AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Documentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/Tab:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 100

Style/EmptyMethod:
  Enabled: false
