# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52614b1e269b770c7fef57f785a6a7c75b15938cab43c1c9389ce2179edf367bad9d62db6952e08bb277b2d6214bc03bf87f8f903d2a5a50598c7185ea1c155d

test:
  secret_key_base: 920486de53043470509eca405054bcdce7f989c3b4919aa4faed4f1bf585145034f2f61af3fe1ce6f6d6d05e91ec37e3df76440eb1edcda00e3440941e8c8b4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
